name: Java CI with Maven

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: set version
        run: git describe --tags --abbrev=0 |sed 's/v\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)/\3/' | xargs echo 1 + | bc | xargs -I{} echo REVISION={} >> $GITHUB_ENV
      - name: Build
        run: mvn -B clean compile -Drevision="$REVISION-SNAPSHOT"
      - name: Test
        run: mvn -B test -Drevision="$REVISION-SNAPSHOT"
